# Flexible User-extensible Simulation Editor (FUSE)
# Copyright (c) 2026 PKB Research Labs, LLC.
#
# This file is part of FUSE.
#
# FUSE is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or, at your option, any later
# version.
from __future__ import annotations

from pathlib import Path
import re


def _clean_identifier(value: str, fallback: str) -> str:
    text = re.sub(r"\W+", "_", str(value or "").strip()).strip("_")
    if not text:
        text = fallback
    if text[0].isdigit():
        text = f"_{text}"
    return text.lower()


def _literal(value) -> str:
    text = str(value if value is not None else "").strip()
    if text == "":
        return "''"
    if re.fullmatch(r"-?\d+", text):
        return text
    if re.fullmatch(r"-?\d+\.\d+", text):
        return text
    if text in {"True", "False", "None"}:
        return text
    return repr(text)


def _parameter(node, name: str, default: str = "") -> str:
    value = getattr(node, "parameters", {}).get(name, default)
    if value is None:
        return default
    return str(value).strip() or default


def _gem5_nodes(scene) -> list:
    return [
        node
        for node in scene.component_items()
        if getattr(getattr(node, "component", None), "plugin_id", "") == "gem5"
    ]


def _node_type(node) -> str:
    return getattr(node.component, "name", "") or getattr(node.component, "display_name", "")


def _node_var(node) -> str:
    return _clean_identifier(getattr(node, "instance_name", ""), f"node_{getattr(node, 'node_id', 0)}")


def _port_iface(node, port_name: str) -> str:
    for port in getattr(node, "ports", []):
        if getattr(port, "name", "") != port_name:
            continue
        metadata = getattr(port, "metadata", {}) or {}
        return (metadata.get("iface") or metadata.get("interface") or "").strip()
    return ""


def _link_assignment(source, source_port: str, target, target_port: str, node_paths: dict[int, str]) -> str:
    source_path = f"{node_paths[source.node_id]}.{source_port}"
    target_path = f"{node_paths[target.node_id]}.{target_port}"
    source_iface = _port_iface(source, source_port)
    target_iface = _port_iface(target, target_port)

    # gem5 Python configs typically assign the request-side port to the
    # response-side port. When metadata is missing, preserve the drawn direction.
    if source_iface == "request_port" and target_iface == "response_port":
        return f"{source_path} = {target_path}"
    if source_iface == "response_port" and target_iface == "request_port":
        return f"{target_path} = {source_path}"
    return f"{source_path} = {target_path}"


def build_gem5_python(scene) -> str:
    """Build a gem5 Python configuration from a gem5-only FUSE scene.

    The exporter intentionally targets the subset of gem5 SimObjects currently
    exposed by the community gem5 plugin. It produces an editable Python config
    rather than replacing FUSE's native .fse project format.
    """
    nodes = _gem5_nodes(scene)
    if not nodes:
        raise ValueError("There are no gem5 components to export.")

    non_gem5 = [
        getattr(node, "instance_name", "<unnamed>")
        for node in scene.component_items()
        if getattr(getattr(node, "component", None), "plugin_id", "") != "gem5"
    ]
    if non_gem5:
        raise ValueError(
            "Gem5 Python export only supports gem5 components. "
            f"Unsupported components: {', '.join(non_gem5)}"
        )

    system_nodes = [node for node in nodes if _node_type(node) == "System"]
    if len(system_nodes) != 1:
        raise ValueError("Gem5 Python export requires exactly one System component.")

    system_node = system_nodes[0]
    node_paths: dict[int, str] = {system_node.node_id: "system"}
    lines: list[str] = [
        "# Generated by FUSE. Edit as needed before production simulation runs.",
        "import m5",
        "from m5.objects import *",
        "",
        "system = System()",
        "system.clk_domain = SrcClockDomain()",
        "system.clk_domain.voltage_domain = VoltageDomain()",
        f"system.clk_domain.clock = {_literal(_parameter(system_node, 'clock', '1GHz'))}",
        f"system.mem_mode = {_literal(_parameter(system_node, 'mem_mode', 'timing'))}",
        f"system.cache_line_size = {_literal(_parameter(system_node, 'cache_line_size', '64'))}",
        f"system.mem_ranges = [AddrRange({_literal(_parameter(system_node, 'mem_ranges', '512MiB'))})]",
        "",
    ]

    for node in nodes:
        if node is system_node:
            continue

        var = _node_var(node)
        node_paths[node.node_id] = f"system.{var}"
        type_name = _node_type(node)

        if type_name == "DDR3_1600_8x8":
            lines.append(f"system.{var} = MemCtrl()")
            lines.append(f"system.{var}.dram = DDR3_1600_8x8()")
            lines.append(f"system.{var}.dram.range = system.mem_ranges[0]")
        else:
            lines.append(f"system.{var} = {type_name}()")

        for name, value in sorted(getattr(node, "parameters", {}).items()):
            if value is None or str(value).strip() == "":
                continue
            if type_name == "DDR3_1600_8x8" and name == "range":
                lines.append(f"system.{var}.dram.range = AddrRange({_literal(value)})")
            elif name == "clock" and "CPU" in type_name:
                lines.append(f"system.{var}.clk_domain = SrcClockDomain()")
                lines.append(f"system.{var}.clk_domain.voltage_domain = VoltageDomain()")
                lines.append(f"system.{var}.clk_domain.clock = {_literal(value)}")
            else:
                lines.append(f"system.{var}.{name} = {_literal(value)}")
        lines.append("")

    nodes_by_id = {node.node_id: node for node in nodes}
    link_lines: list[str] = []
    for link in getattr(scene, "links", []):
        source = nodes_by_id.get(link.source_node_id)
        target = nodes_by_id.get(link.target_node_id)
        if source is None or target is None:
            continue
        link_lines.append(
            _link_assignment(source, link.source_port, target, link.target_port, node_paths)
        )

    if link_lines:
        lines.append("# Port connections")
        lines.extend(link_lines)
        lines.append("")

    lines.extend(
        [
            "root = Root(full_system=False, system=system)",
            "m5.instantiate()",
            "print('FUSE-generated gem5 configuration instantiated successfully')",
            "event = m5.simulate()",
            "print(f'Exiting @ tick {m5.curTick()} because {event.getCause()}')",
            "",
        ]
    )
    return "\n".join(lines)


def export_gem5_python(scene, output_path: str | Path) -> None:
    path = Path(output_path)
    path.write_text(build_gem5_python(scene), encoding="utf-8")
