# Flexible User-extensible Simulation Editor (FUSE)
# Copyright (c) 2026 PKB Research Labs, LLC.
#
# This file is part of FUSE.
"""Import bundled SST component metadata catalogs into the FUSE database.

The component catalogs are JSON snapshots generated by the existing sst-info
parser on a maintainer machine. Normal FUSE setup imports these JSON files into
SQLite so the existing palette/component-list code can keep querying the DB.
"""

from __future__ import annotations

import os
from pathlib import Path

from fuse.core.persistence.database import get_connection
from fuse.plugins.community.sst.get_sstinfo import sync_sstinfo_catalog_json_to_database
from fuse.plugins.community.sst.policy.loader import (
    available_policy_catalog_versions,
    has_policy_catalog,
    normalize_sst_version,
)


_COMPONENT_CATALOG_DIR = Path(__file__).resolve().parent / "component_catalogs"


def _version_sort_key(version: str) -> tuple[int, ...]:
    try:
        return tuple(int(part) for part in normalize_sst_version(version).split("."))
    except ValueError:
        return (0,)


def component_catalog_path_for_version(version: str) -> Path:
    normalized = normalize_sst_version(version)
    return _COMPONENT_CATALOG_DIR / f"sst-{normalized}.json"


def available_component_catalog_versions() -> list[str]:
    """Return SST versions that have bundled component metadata catalogs."""

    if not _COMPONENT_CATALOG_DIR.exists():
        return []

    versions: list[str] = []

    for path in _COMPONENT_CATALOG_DIR.glob("sst-*.json"):
        version = normalize_sst_version(path.stem.removeprefix("sst-"))
        if version:
            versions.append(version)

    return sorted(versions, key=_version_sort_key)


def has_component_catalog(version: str | None) -> bool:
    """Return true when FUSE ships component metadata for the requested SST version."""

    normalized = normalize_sst_version(version)

    if not normalized:
        return False

    return component_catalog_path_for_version(normalized).exists()


def _component_count_for_version(version: str) -> int:
    with get_connection() as conn:
        row = conn.execute(
            """
            SELECT COUNT(*) AS count
            FROM sst_components c
            JOIN sst_framework_versions fv
              ON c.framework_version_id = fv.id
            WHERE fv.version = ?
            """,
            (version,),
        ).fetchone()

    return int(row["count"]) if row is not None else 0


def import_bundled_component_catalogs() -> None:
    """Import bundled SST component catalogs into the database.

    This runs during plugin/bootstrap setup. It reads JSON only; it does not run
    sst-info. The normal component catalog/list panel continues to query the
    database exactly as before.
    """

    force_refresh = os.environ.get(
        "FUSE_REFRESH_BUNDLED_SST_COMPONENT_CATALOGS",
        "0",
    ) == "1"

    component_versions = available_component_catalog_versions()

    if not component_versions:
        print("SST plugin: no bundled SST component metadata catalogs were found.")
        return

    policy_versions = set(available_policy_catalog_versions())
    default_candidates = sorted(
        policy_versions.intersection(component_versions) or set(component_versions),
        key=_version_sort_key,
    )
    default_version = default_candidates[-1] if default_candidates else component_versions[-1]

    for version in component_versions:
        if not has_policy_catalog(version):
            print(
                f"SST plugin: component catalog for SST {version} has no matching "
                "policy catalog; skipping."
            )
            continue

        if not force_refresh and _component_count_for_version(version) > 0:
            continue

        sync_sstinfo_catalog_json_to_database(
            path=component_catalog_path_for_version(version),
            version=version,
            label=f"SST {version}",
            is_default=(version == default_version),
        )
