[pytest]
testpaths =
    tests
    plugins/community/gem5/tests
    plugins/community/sst/tests
python_files = test_*.py
qt_api = pyside6
norecursedirs =
    .venv
    __pycache__
    .git
    app_data